package com.fazendapro.financeiro.model;
public enum CategoriaFinanceiro {
    VENDA_LEITE, VENDA_ANIMAL, COMPRA_ANIMAL, COMPRA_RACAO,
    COMPRA_MEDICAMENTO, VACINA, MAQUINARIO, ENERGIA, MAOOBRA,
    MANUTENCAO, FRETE, OUTROS_RECEITA, OUTROS_DESPESA
}
